# Generated by Django 5.2 on 2025-07-12 15:07

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('original_file', models.FileField(upload_to=documents.models.user_document_path)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('page_count', models.IntegerField(default=0)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('processing', '处理中'), ('processed', '已处理'), ('failed', '处理失败')], default='uploaded', max_length=20)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('ocr_data', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_hash', models.CharField(max_length=64, unique=True)),
                ('config_data', models.JSONField()),
                ('processed_file', models.FileField(blank=True, null=True, upload_to=documents.models.processed_document_path)),
                ('process_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '等待处理'), ('processing', '处理中'), ('completed', '处理完成'), ('failed', '处理失败')], default='pending', max_length=20)),
                ('total_fields', models.IntegerField(default=0)),
                ('processed_fields', models.IntegerField(default=0)),
                ('failed_fields', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_versions', to='documents.document')),
            ],
            options={
                'ordering': ['-process_time'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=50)),
                ('processing_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('skipped', '跳过')], max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='documents.processeddocument')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
