# Generated by Django 5.2 on 2025-07-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddocument',
            name='config_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='processeddocument',
            unique_together={('document', 'config_hash')},
        ),
    ]
